version: "3"

services:

  mongo:
    container_name: event_mongo
    image: mongo
    networks:
      - webnet
    volumes:
      - ./.docker/mongo:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  redis:
    container_name: event_redis
    image: redis
    volumes:
      - ./.docker/redis:/redis/db
    networks:
      - webnet
    ports:
      - "${REDIS_PORT}:6379"

networks:
  webnet: